### ISSUE TITLE
We need to clean up internal structure of eden config file

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#75]
Looking at the current structure of the Eden config file it becomes clear that we need to do a bit of refactoring to make it understandable by "mere mortals" in the EVE development community. I suggest we do at least the following:

Focus on Eden workflows that assume that Eden doesn't ever "rebuild" anything by itself. If Eden needs some kind of an artifact it needs to be already present as a file or a docker container on the developer's desktop (that is not to say that we will be killing this functionality in Eden -- just that we're not going to focus on it for now). If we assume that -- we can them restructure the sequence of various settings in the config file so that the ones that have to do with building (or any other complicated workflow get to be listed AFTER the ones that developers may actually be interested in tweaking.

With this in mind, here's what I propose Eden default config should look like. NOTE that lines with XXX comments are my questions about something -- please answer those. Lines with MOVED-FROM show what options I propose we move from some other part of Eden config:

```
#config is generated by eden
adam:
    #tag on adam container to pull
    tag: 0.0.44

    #port of adam
    port: 3333

    #domain of adam
    domain: mydomain.adam

    #ip of adam for EVE access
    eve-ip: 192.168.0.2

    #ip of adam for EDEN access
    ip: 10.0.0.247

    #URL of RedisDB for Adam to talk to (MOVED-FROM adam.redis.adam)
    redis-url: redis://10.0.0.247:6379

    #certificate for communication with adam
    ca: adam/run/config/root-certificate.pem

# From this point on, all the rest of the settings are "internal" for Adam -- tweak at your own risk

    #location of adam XXX - do we need this if we are NOT building Adam?
    dist: adam

     #force adam rebuild XXX note that the new setting is false -- will this break anything?
     force: false

    #use remote adam
    remote:
        enabled: true

        #load logs and info from redis instead of http stream
        redis: true

    #use v1 api
    v1: true

eve:
    #live image of EVE: this is a baseOS version for the initial image
    #XXX: note that this is the only thing that Eden needs to know about how to launch
    #EVE instance -- we don't even need to know the version of it
    image-file: eve/dist/amd64/live.qcow2

    #devmodel
    devmodel: Qemu

    #file to save qemu config
    qemu-config: /Users/roman/.eden/qemu.conf

    #EVE arch (amd64/arm64)
    arch: amd64

    #EVE acceleration (set to false if you have problems with qemu)
    accel: true

    #uuid of EVE to use in cert
    uuid: 2b72e180-7e85-4cd9-b4b5-13af35de1be7

    #serial number in SMBIOS
    serial: 31415926

    #onboarding certificate of EVE to put into adam
    cert: certs/onboard.cert.pem

    #EVE firmware
    firmware: eve/dist/amd64/OVMF.fd

    #forward of ports in qemu [(HOST:EVE)]
    hostfwd:
        2222: 22
        5912: 5901
        5911: 5900
        8027: 8027
        8028: 8028

# From this point on, all the rest of the settings are "internal" for Eve -- tweak at your own risk

    #location of eve directory
    dist: eve

    #location of EVE base os directory
    base-dist: evebaseos

    #dtb directory of EVE
    dtb-part:

    #EVE pid file
    pid: eve.pid

    #EVE log file
    log: eve.log

    #eve repo used in clone mode (eden.download = false)
    repo: https://github.com/lf-edge/eve.git

    #eve tag -- XXX we only need this for tests, correct?
    tag: 5ee6043906449f7fa3447c96fd38dc9a536c5693

    #eve tag for base os -- XXX we only need this for tests, correct?
    base-tag: 571d94a11fa19d79805a0465030175b7257d343b

    #eve version (without hv and os) -- XXX we only need this for tests, correct?
    base-version: 0.0.0-snapshot-master-93c2dbb2-2020-05-08.13.15

    #config part of EVE -- XXX this can be killed now, correct?
    config-part: adam/run/config

    #variant of hypervisor of EVE (kvm/xen) -- XXX why do we need this option if we don't rebuild
    hv: kvm

    #EVE os (linux/darwin) -- XXX why do we need this option?
    os: darwin

eden:
    #root directory of eden
    root: /Users/roman/src/lfe/eden/dist

    #URL of RedisDB for Eden to talk to (MOVED-FROM adam.redis.eden)
    redis-url: redis://10.0.0.247:6379

    #caching logs and info to redis instead of local (MOVED-FROM adam.caching.*)
    events-caching:
        enabled: false

        #cache from redis
        redis: false

        #prefix for directory/redis stream
        prefix: cache

    images:
        #directory to save images
        dist: images

        #yml to build docker image
        docker: /Users/roman/src/lfe/eden/images/docker/alpine/alpine.yml

        #yml to build vm image
        vm: /Users/roman/src/lfe/eden/images/vm/alpine/alpine.yml

    #download eve instead of build
    download: true

    #directory to save certs
    certs-dist: certs

    #directory to save binaries
    bin-dist: bin

    #ssh-key to put into EVE
    ssh-key: certs/id_rsa.pub

    #observe logs in tests
    logs: false

    #eden binary
    eden-bin: eden

    #test binary
    test-bin: eden.integration.test

    #test script
    test-script: eden.integration.tests.txt

redis:
    #port for access redis
    port: 6379

    #tag for redis image
    tag: 6

    #directory to use for redis persistence
    dist: redis

#eserver is tool for serve images (MOVED-FROM: eden.eserver)
eserver:
        #ip (domain name) of eserver for EVE access
        ip: mydomain.adam

        #port for eserver
        port: 8888

        #pid for eserver
        pid: eserver.pid

        #log of eserver
        log: eserver.log
```
