### ISSUE TITLE
Split eden test workflows

### ISSUE THREAD

**Issue by uncleDecart** [lf-edge/eden#863]
### What

Currently we run all “[default](https://github.com/lf-edge/eden/tree/master/tests/workflow#workflow-test-scenarios)” eden tests together as one [workflow](https://github.com/lf-edge/eve/blob/master/.github/workflows/eden.yml).

This workflow has four variants defined by matrix: [zfs/ext4 + TPM/no-TPM](https://github.com/lf-edge/eve/blob/master/.github/workflows/eden.yml#L22-L24)

The problem is that the overall time needed to execute all these tests is close to the overall timeout of 6hrs and sometimes we see this workflow being canceled by github as the timeout is exceeded.

Another problem is that such long workflow is very impractical to work with. If we get a failure after 3hrs of workflow runtime and decide to restart (on the assumption that it was false negative), we have to wait another 3hrs to see if the failure is repeated and 1-2 hrs more to get completed successful run.

Third problem with the current setup is that we are wasting time by running some of the long tests with all four matrix variants. For example, for networking tests it is irrelevant which filesystem is being used and whether TPM is available.

### Outcomes 

5 separate workflows (respective PR's will be linked here) and respective github actions

### Related PRs

- #864 
- #869

**Comment by milan-zededa** [comment]
@uncleDecart This seems to be done. The only missing thing is to switch from the old to the new workflows in this eden repository (just like we did in eve repo).

**Comment by uncleDecart** [comment]
I wonder if we will have to modify eve workflow again to avoid duplicates @milan-zededa , because we will have to add something like this 

```yml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_suite_pr:
    if: github.event.review.state == 'approved'
    uses: lf-edge/eden/.github/workflows/test.yml@0.9.2
    with:
      eve_image: "evebuild/danger:pr${{ github.event.pull_request.number  }}"

  test_suite_master:
    if: github.ref == 'refs/heads/master'
    uses: lf-edge/eden/.github/workflows/test.yml@0.9.2
    with:
      eve_image: "lfedge/eve:snapshot"
```

which is actually eve workflow and we again hit duplicating work (less than before, but still). We need to run tests on master and on every PR in eden repo as well

Btw, @yash-zededa in EVE workflow, do we really need?

```
  test_suite_tag:
    if: startsWith(github.ref, 'refs/tags')
    uses: lf-edge/eden/.github/workflows/test.yml@0.9.2
    with:
      eve_image: "lfedge/eve:${{ github.ref_name }}"
```
