### ISSUE TITLE
Workflows: Improve tpm part of test.yml name

### ISSUE THREAD

**Issue by uncleDecart** [lf-edge/eden#930]
### What

Currently, jobs in test.yml are running following matrix:
```yaml
  smoke:
    continue-on-error: true
    strategy:
      matrix:
        file_system: ['ext4', 'zfs']
        tpm: [true, false]
```

Which generates following name:
 ```Smoke tests (ext4, false)```
We want it to be something more meaningful like :
``` Smoke tests (ext4, no-tpm)```

### How can we do that?

We can change tpm from boolean parameter to string and compare it to string throughout the test.yml.

Alternatively, if there's a way to change job names to 
```yml
  smoke:
    continue-on-error: true
    strategy:
      matrix:
        file_system: ['ext4', 'zfs']
        tpm: [true, false]
    name: "Smoke tests ${{ matrix.file_system }} tpm-enabled : ${{ matrix.tpm }}
```

I prefer the latter, because it's less work and boolean comparison remains
